### ISSUE TITLE
Predictive text in Choosing Facsimiles for Artefacts

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#144]
When searching for facsimiles, predictive text prompts original file names, and not the Titles added in metadata. Should this search for both?

**Comment by AnnaGerber** [comment]
Was searching both fields, just not displaying title. Titles were deliberately no longer displayed in the search field because of user feedback (because titles tend to get long)

Code now updated to display title when searching but not after the tag has been attached to the field in the record (title is display on hover over the filename in the field)
