### ISSUE TITLE
Highlighting in MVD points to whitespace

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#189]
MVD side-by-side view on AustESE highlights white-space (picking up underlying code???). Can this be avoided. It doesn't happen on Calliope test pages with character highlighting.

![mvd spaces copy](https://f.cloud.github.com/assets/1567062/1197218/62d019a8-24cf-11e3-8ffa-ffff17bfa3ea.jpg)

**Comment by AnnaGerber** [comment]
Calliope is generating markup there to indicate additions/deletions - in this case I think it might be because the line breaks  and white spaces are different in the source text files.

I've changed the default presentation to use character highlighting instead of background highlighting to avoid them showing up
