### ISSUE TITLE
Update Membership for Membership Request Fails

### ISSUE THREAD

**Issue by tomcollinsandcompany** [uq-eresearch/AustESE#227]
Dean Irvine's request for membership in AustESE Workshop II was not completed when updating. It is still pending.

**Comment by AnnaGerber** [comment]
I've set his membership to active. 
If this happens for anyone else you can change their membership - go to the project tab and select people. Check the box next to a person. Select 'Modify membership status' from the operations menu at the top, then click Execute. Change their status to Active rather than Pending and save.
